name: Docker CI 

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: bootJar

      - name: Copy Jar file
        run: mv build/libs/*.jar app.jar

      - name: Upload Jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar-file
          path: app.jar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set env
        run: echo "DATE=$(date +%s)" >> $GITHUB_ENV

      - name: Download Jar artifact
        uses: actions/download-artifact@v2
        with:
          name: jar-file
          path: app.jar

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: etlison/demo-app:${{ env.DATE }}
